### ISSUE TITLE
 An error occurred when I called this component

### ISSUE THREAD

**Issue by watermelon0314** [tienphaw/react-native-figma-squircle#1]
![image](https://user-images.githubusercontent.com/82018215/122718550-a97b5f80-d29f-11eb-8d5e-2ba640e845b2.png)
![image](https://user-images.githubusercontent.com/82018215/122718843-fbbc8080-d29f-11eb-915a-fb7acc299c65.png)

**Comment by phamfoo** [comment]
Hi @watermelon0314,
Can you create a github repo or a [snack](https://snack.expo.io/) for me to look at?

**Comment by watermelon0314** [comment]
I tried to change the code in ./src/index.tsx
deleted
<img width="382" alt="image" src="https://user-images.githubusercontent.com/82018215/122867679-764ad600-d35c-11eb-9dc9-a8f9ff67029a.png">
then added export in front of interface SquircleParams and function SquircleView
<img width="382" alt="image" src="https://user-images.githubusercontent.com/82018215/122867886-d04b9b80-d35c-11eb-8499-38858326dc57.png">
<img width="382" alt="image" src="https://user-images.githubusercontent.com/82018215/122867908-d5a8e600-d35c-11eb-9a74-dc4e24e02547.png">
and it will take effect.

The effect is very good👍

**Comment by phamfoo** [comment]
This is [an issue from babel-plugin-transform-typescript](https://github.com/babel/babel/issues/6065) and was fixed in [this PR](https://github.com/babel/babel/pull/9944).
I think you might be using an older version of `metro-react-native-babel-preset`.

I moved `SquircleParams` to a type export in `v0.1.2`, please give it a try and let me know if it fixes the issue.

**Comment by phamfoo** [comment]
@watermelon0314  I'm closing this, feel free to reopen if the issue persists.
